version: v3

teleport:
  data_dir: /var/lib/teleport
  log:
    severity: INFO
    output: stdout

auth_service:
  enabled: true
  cluster_name: teleport.takashiaihara.site
  authentication:
    type: local
    second_factors:
      - webauthn
      - otp
    webauthn:
      rp_id: teleport.takashiaihara.site

proxy_service:
  enabled: true
  public_addr: teleport.takashiaihara.site:443
  https_keypairs:
    - key_file: /certs/_.takashiaihara.site.key
      cert_file: /certs/_.takashiaihara.site.crt
  proxy_listener_mode: multiplex
  web_listen_addr: 0.0.0.0:3080

ssh_service:
  enabled: false
